id: dk.ehmi.eer-config
canonical: http://medcomehmi.dk/ig/eer-config
name: EHMI Endpoint Register (EER) IG Configurations
title: "DK EHMI Endpoint Register (EER) - Configurations"
description: The EHMI Endpoint Register (EER) IG - Configurations for merge with incoming  from SOR 
status: draft # draft | active | retired | unknown
version: 1.0.0-draft
fhirVersion: 4.0.1
copyrightYear: 2025+
releaseLabel: ci-build # ci-build | draft | qa-preview | ballot | trial-use | release | update | normative+trial-use
jurisdiction: urn:iso:std:iso:3166#DK "Denmark"
publisher:
  name: MedCom
  url: http://medcom.dk
  email: ehmi@medcom.dk

dependencies:
  ihe.iti.mcsd: 4.0.0
  hl7.fhir.dk.core: 3.4.0
  medcom.fhir.dk.core: 3.0.1
  medcom.fhir.dk.messaging: 4.0.1
  medcom.fhir.dk.terminology: 2.0.1
  dk.ehmi.terminology: 
    version: 1.0.1-draft
    uri: http://medcomehmi.dk/ig/terminology/ImplementationGuide/dk.ehmi.terminology
#  dk.ehmi.eer: current
  dk.ehmi.eer: 
    version: current
    uri: https://build.fhir.org/ig/medcomdk/dk-ehmi-eer/ImplementationGuide/dk.ehmi.eer
#    version: 2.0.0-draft 
#    uri: https://build.fhir.org/ig/medcomdk/dk-ehmi-eer/ImplementationGuide/dk.ehmi.eer
#    uri: http://medcomehmi.dk/ig/eer/ImplementationGuide/dk.ehmi.eer

menu:
  Home: index.html
#  Profiles: profiles.html
  Artifacts: 
    Devices: instances-devices.html
    Endpoints: instances-endpoints.html
    Organizations: instances-organizations.html
    Artifacts: artifacts.html
  More:
    Table of Contents: toc.html
    Downloads: downloads.html
    Dependencies: dependencies.html
#    mCSD User-stories: EHMI-CSD-User-Stories.html

parameters:
  apply-version: false
  default-version: true
  apply-publisher: false
  default-publisher: true
  pin-canonicals: pin-multiples
  excludettl: true